apiVersion: v1
kind: ConfigMap
metadata:
  name: shopnow-discovery-server-application-properties-configmap
  namespace: shopnow
data:
  application.properties: |
    spring.application.name=discovery-server
    server.port=8761
    eureka.client.register-with-eureka=false
    eureka.client.fetch-registry=false
    