apiVersion: v1
kind: ConfigMap
metadata:
  name: shopnow-product-service-application-properties-configmap
  namespace: shopnow
data:
  application.properties: |
    spring.application.name=product-service
    server.port=5861

    eureka.instance.hostname=product-service
    eureka.instance.instance-id=${spring.application.name}
    eureka.client.service-url.defaultZone=http://shopnow-discovery-server-service:8761/eureka/

    spring.datasource.url=jdbc:postgresql://postgres:5432/postgres?useSSL=false
    spring.datasource.username=postgres
    spring.datasource.password=admin
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.format-sql=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shopnow-product-service
  name: shopnow-product-service-deployment
  namespace: shopnow
spec:
  replicas: 1
  revisionHistoryLimit: 11
  selector:
    matchLabels:
      app: shopnow-product-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: shopnow-product-service
      namespace: shopnow
    spec:
      containers:
        - image: thuanlp/shopnow_product-service:v1
          imagePullPolicy: Always
          name: shopnow-product-service
          ports:
            - containerPort: 5861
              name: tcp
              protocol: TCP
          volumeMounts:
            - mountPath: /app/src/main/resources/application.properties
              name: shopnow-product-service-application-properties-config-volume
              subPath: application.properties
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path:  /actuator/health/readiness
              port: 5861
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path:  /actuator/health/liveness
              port: 5861
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 5
      imagePullSecrets:
      - name: dockerhub
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: shopnow-product-service-application-properties-configmap
          name: shopnow-product-service-application-properties-config-volume
          
---
apiVersion: v1
kind: Service
metadata:
  name: shopnow-product-service-service
  namespace: shopnow
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp
      port: 5861
      protocol: TCP
      targetPort: 5861
  selector:
    app: shopnow-product-service
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopnow-product-service-ingress
  namespace: shopnow
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - product-service.lptdevops.website
    secretName: product-service-tls  
  rules:
    - host: product-service.lptdevops.website
      http:
        paths:
          - backend:
              service:
                name: shopnow-product-service-service
                port:
                  number: 5861
            path: /
            pathType: Prefix
