apiVersion: v1
kind: ConfigMap
metadata:
  name: shopnow-user-service-application-properties-configmap
  namespace: shopnow
data:
  application.properties: |
    # Application configuration
    spring.application.name=user-service
    server.port=5865

    eureka.instance.hostname=user-service
    eureka.instance.instance-id=${spring.application.name}
    eureka.client.service-url.defaultZone=http://shopnow-discovery-server-service:8761/eureka/

    # Datasource configuration
    spring.datasource.url=jdbc:postgresql://postgres:5432/postgres?useSSL=false
    spring.datasource.username=postgres
    spring.datasource.password=admin
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.format-sql=true

    # JWT configuration
    jwt.issuer_uri=http://shopnow-keycloak-realms-service:8080/realms/java-microservice-realm/protocol/openid-connect/token
    jwt.client_id=spring-cloud-client
    jwt.client_secret=AJufwN1eof8P5Gga5Y9atCFqdMuZEuKd
    jwt.grant_type=client_credentials
    jwt.scope=openid offline_access